# Generated by Django 3.1.3 on 2020-11-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('body', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.CharField(max_length=200, null=True)),
                ('topic', models.CharField(choices=[('Iman', 'Iman'), ('Quran', 'Quran'), ('Hadith', 'Hadith'), ('Taohid', 'Taohid'), ('Salat', 'Salat')], max_length=200)),
            ],
        ),
    ]
