# Generated by Django 3.1.3 on 2020-11-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
